In [1]:
import pandas as pd 
import sqlite3

In [2]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
conn = sqlite3.connect('project3.db')

In [4]:
df.to_sql('Orders', conn, if_exists='replace', index=False)

1200

In [5]:
pd.read_sql(""" SELECT* FROM Orders LIMIT 5 """, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [9]:
pd.read_sql("""
SELECT COUNT(*) AS TotalOrders
FROM Orders
""", conn)

   TotalOrders
0         1200

In [12]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\users\shubh\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (9.7.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (2.0.43)
Requirement already satisfied: sqlparse in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\shubh\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\shubh\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shubh\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\shubh\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\shubh\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\shubh\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\shubh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\shubh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\shubh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)

In [16]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [18]:
%sql sqlite:///project3.db

In [23]:
%reload_ext sql

In [26]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [27]:
%%sql
SELECT COUNT(*) AS TotalOrders
FROM Orders;

 * sqlite:///project3.db
Done.

[(1200,)]

Observation:
The Orders table contains 1200 records.

Insight:
The dataset consists of 1200 customer orders available for analysis.

In [28]:
%%sql
SELECT AVG(TotalPrice) AS Averageordervalue FROM Orders;

 * sqlite:///project3.db
Done.

[(1053.9683,)]

Insight:
Customers spend approximately ₹1054 per order on average.

In [29]:
%%sql 
SELECT SUM(TotalPrice) AS TotalRevenue FROM Orders;

 * sqlite:///project3.db
Done.

[(1264761.96,)]

Observation:
The total revenue generated from all orders is ₹12,64,761.96.
    
Insight:
The business generated approximately ₹12.65 lakh in revenue from 1200 customer orders.

In [31]:
%%sql 
SELECT Product, COUNT(*) AS TotalOrders FROM Orders
GROUP BY Product;

 * sqlite:///project3.db
Done.

[('Chair', 178),
 ('Desk', 170),
 ('Laptop', 173),
 ('Monitor', 163),
 ('Phone', 156),
 ('Printer', 181),
 ('Tablet', 179)]

In [32]:
%%sql
SELECT Product,
COUNT(*) AS TotalOrders
FROM Orders
GROUP BY Product
ORDER BY TotalOrders DESC;

 * sqlite:///project3.db
Done.

[('Printer', 181),
 ('Tablet', 179),
 ('Chair', 178),
 ('Laptop', 173),
 ('Desk', 170),
 ('Monitor', 163),
 ('Phone', 156)]

Observation:
Printer has the highest number of orders (181), while Phone has the lowest number of orders (156).

Insight:
Printer is the most popular product among customers, while Phone has the lowest demand in the dataset.

In [33]:
%%sql 
SELECT*FROM Orders 
Where OrderStatus='Delivered';

 * sqlite:///project3.db
Done.

[('ORD200004', '2025-05-08 00:00:00', 'C81840', 'Printer', 4, 626.01, '668 Main St', 'Online', 'Delivered', 'TRK29241424', 8, 'SAVE10', 'Email', 2504.04),
 ('ORD200015', '2023-07-17 00:00:00', 'C39416', 'Printer', 1, 473.96, '942 Main St', 'Cash', 'Delivered', 'TRK54930938', 3, None, 'Google', 473.96),
 ('ORD200021', '2024-11-17 00:00:00', 'C99023', 'Monitor', 4, 342.95, '569 Main St', 'Cash', 'Delivered', 'TRK52646983', 6, None, 'Google', 1371.8),
 ('ORD200024', '2024-10-30 00:00:00', 'C17470', 'Laptop', 2, 230.95, '956 Main St', 'Online', 'Delivered', 'TRK28775057', 3, 'WINTER15', 'Referral', 461.9),
 ('ORD200025', '2024-07-24 00:00:00', 'C42577', 'Monitor', 1, 399.98, '709 Main St', 'Debit Card', 'Delivered', 'TRK69423327', 3, 'WINTER15', 'Email', 399.98),
 ('ORD200026', '2024-03-06 00:00:00', 'C21944', 'Laptop', 5, 59.55, '296 Main St', 'Online', 'Delivered', 'TRK80276812', 6, None, 'Referral', 297.75),
 ('ORD200029', '2024-09-20 00:00:00', 'C33260', 'Desk', 3, 423.53, '930 Main St', 'Credit Card', 'Delivered', 'TRK59744090', 6, 'SAVE10', 'Referral', 1270.59),
 ('ORD200032', '2023-05-01 00:00:00', 'C12388', 'Tablet', 5, 536.72, '830 Main St', 'Cash', 'Delivered', 'TRK99261395', 10, None, 'Email', 2683.6),
 ('ORD200038', '2024-12-19 00:00:00', 'C15924', 'Laptop', 1, 245.89, '549 Main St', 'Debit Card', 'Delivered', 'TRK14835975', 3, 'SAVE10', 'Google', 245.89),
 ('ORD200039', '2025-02-27 00:00:00', 'C96664', 'Printer', 3, 256.46, '666 Main St', 'Credit Card', 'Delivered', 'TRK85508960', 4, 'SAVE10', 'Referral', 769.3799999999999),
 ('ORD200040', '2023-08-20 00:00:00', 'C84766', 'Desk', 2, 344.02, '267 Main St', 'Online', 'Delivered', 'TRK78967923', 4, 'FREESHIP', 'Instagram', 688.04),
 ('ORD200061', '2024-03-24 00:00:00', 'C61618', 'Desk', 4, 122.2, '104 Main St', 'Cash', 'Delivered', 'TRK43458485', 7, 'FREESHIP', 'Facebook', 488.8),
 ('ORD200065', '2023-12-30 00:00:00', 'C97735', 'Monitor', 5, 81.7, '385 Main St', 'Credit Card', 'Delivered', 'TRK13743703', 6, None, 'Instagram', 408.5),
 ('ORD200075', '2023-09-26 00:00:00', 'C80651', 'Tablet', 3, 398.17, '917 Main St', 'Debit Card', 'Delivered', 'TRK14846720', 5, 'SAVE10', 'Email', 1194.51),
 ('ORD200078', '2024-08-06 00:00:00', 'C32029', 'Printer', 4, 175.36, '146 Main St', 'Debit Card', 'Delivered', 'TRK68535532', 4, 'FREESHIP', 'Instagram', 701.44),
 ('ORD200085', '2024-09-09 00:00:00', 'C14553', 'Tablet', 3, 146.73, '768 Main St', 'Cash', 'Delivered', 'TRK93538334', 8, 'FREESHIP', 'Email', 440.1899999999999),
 ('ORD200090', '2023-09-18 00:00:00', 'C36540', 'Chair', 4, 182.08, '611 Main St', 'Gift Card', 'Delivered', 'TRK35828122', 4, 'SAVE10', 'Email', 728.32),
 ('ORD200096', '2024-06-01 00:00:00', 'C93007', 'Phone', 2, 232.83, '103 Main St', 'Gift Card', 'Delivered', 'TRK85696091', 7, None, 'Instagram', 465.66),
 ('ORD200100', '2023-02-17 00:00:00', 'C74866', 'Phone', 3, 664.79, '743 Main St', 'Online', 'Delivered', 'TRK53783265', 6, None, 'Facebook', 1994.37),
 ('ORD200104', '2024-07-30 00:00:00', 'C65744', 'Phone', 1, 582.04, '647 Main St', 'Gift Card', 'Delivered', 'TRK39906058', 1, 'FREESHIP', 'Email', 582.04),
 ('ORD200108', '2024-12-28 00:00:00', 'C33099', 'Laptop', 5, 48.38, '522 Main St', 'Gift Card', 'Delivered', 'TRK28522330', 9, 'WINTER15', 'Email', 241.9),
 ('ORD200123', '2023-07-06 00:00:00', 'C86064', 'Desk', 3, 278.04, '727 Main St', 'Online', 'Delivered', 'TRK62182901', 5, None, 'Instagram', 834.1200000000001),
 ('ORD200128', '2023-02-17 00:00:00', 'C86408', 'Tablet', 4, 21.07, '244 Main St', 'Gift Card', 'Delivered', 'TRK41432648', 4, 'FREESHIP', 'Google', 84.28),
 ('ORD200137', '2024-11-26 00:00:00', 'C50682', 'Monitor', 2, 250.98, '598 Main St', 'Credit Card', 'Delivered', 'TRK12242337', 5, None, 'Google', 501.96),
 ('ORD200140', '2025-05-31 00:00:00', 'C33110', 'Chair', 3, 528.14, '388 Main St', 'Online', 'Delivered', 'TRK38624225', 3, 'FREESHIP', 'Email', 1584.42),
 ('ORD200145', '2024-03-02 00:00:00', 'C85929', 'Printer', 3, 146.91, '798 Main St', 'Credit Card', 'Delivered', 'TRK29318610', 6, 'FREESHIP', 'Google', 440.73),
 ('ORD200149', '2023-12-27 00:00:00', 'C39671', 'Laptop', 1, 217.56, '174 Main St', 'Debit Card', 'Delivered', 'TRK47153818', 3, None, 'Facebook', 217.56),
 ('ORD200156', '2024-11-08 00:00:00', 'C58808', 'Chair', 2, 269.83, '651 Main St', 'Online', 'Delivered', 'TRK24451893', 4, 'SAVE10', 'Email', 539.66),
 ('ORD200166', '2025-03-04 00:00:00', 'C28889', 'Chair', 3, 86.29, '565 Main St', 'Cash', 'Delivered', 'TRK23791726', 6, 'WINTER15', 'Instagram', 258.87),
 ('ORD200169', '2024-04-07 00:00:00', 'C35785', 'Printer', 1, 427.82, '732 Main St', 'Online', 'Delivered', 'TRK78923089', 2, 'WINTER15', 'Email', 427.82),
 ('ORD200171', '2023-08-15 00:00:00', 'C20448', 'Tablet', 2, 148.22, '336 Main St', 'Credit Card', 'Delivered', 'TRK67379895', 7, 'WINTER15', 'Instagram', 296.44),
 ('ORD200172', '2025-04-06 00:00:00', 'C34134', 'Printer', 1, 254.12, '365 Main St', 'Online', 'Delivered', 'TRK43074303', 1, 'WINTER15', 'Email', 254.12),
 ('ORD200173', '2024-03-24 00:00:00', 'C95901', 'Phone', 3, 664.46, '806 Main St', 'Online', 'Delivered', 'TRK56989066', 4, 'FREESHIP', 'Google', 1993.38),
 ('ORD200174', '2024-04-16 00:00:00', 'C51145', 'Printer', 4, 600.81, '790 Main St', 'Debit Card', 'Delivered', 'TRK59154274', 9, 'SAVE10', 'Email', 2403.24),
 ('ORD200178', '2024-04-11 00:00:00', 'C53070', 'Chair', 4, 512.06, '283 Main St', 'Online', 'Delivered', 'TRK49791755', 5, 'SAVE10', 'Google', 2048.24),
 ('ORD200179', '2024-11-24 00:00:00', 'C27401', 'Laptop', 3, 539.91, '500 Main St', 'Credit Card', 'Delivered', 'TRK14332053', 8, None, 'Email', 1619.73),
 ('ORD200183', '2024-04-18 00:00:00', 'C39246', 'Monitor', 5, 186.28, '258 Main St', 'Debit Card', 'Delivered', 'TRK16658182', 8, 'SAVE10', 'Email', 931.4),
 ('ORD200196', '2025-01-24 00:00:00', 'C40882', 'Desk', 4, 217.13, '719 Main St', 'Cash', 'Delivered', 'TRK64165503', 8, 'WINTER15', 'Email', 868.52),
 ('ORD200200', '2025-06-07 00:00:00', 'C97681', 'Tablet', 5, 433.26, '895 Main St', 'Credit Card', 'Delivered', 'TRK37531040', 9, 'SAVE10', 'Google', 2166.3),
 ('ORD200207', '2025-03-18 00:00:00', 'C54595', 'Phone', 1, 121.96, '999 Main St', 'Debit Card', 'Delivered', 'TRK44416659', 3, None, 'Google', 121.96),
 ('ORD200210', '2024-12-05 00:00:00', 'C93821', 'Chair', 3, 358.48, '513 Main St', 'Gift Card', 'Delivered', 'TRK10658539', 7, 'FREESHIP', 'Facebook', 1075.44),
 ('ORD200214', '2024-08-21 00:00:00', 'C29483', 'Desk', 4, 305.72, '673 Main St', 'Online', 'Delivered', 'TRK89423603', 5, None, 'Facebook', 1222.88),
 ('ORD200219', '2025-05-02 00:00:00', 'C48946', 'Laptop', 5, 61.97, '457 Main St', 'Cash', 'Delivered', 'TRK99387220', 6, 'SAVE10', 'Email', 309.85),
 ('ORD200226', '2025-06-27 00:00:00', 'C31501', 'Desk', 3, 588.05, '242 Main St', 'Gift Card', 'Delivered', 'TRK93063929', 8, None, 'Instagram', 1764.15),
 ('ORD200229', '2025-03-28 00:00:00', 'C62622', 'Tablet', 1, 562.61, '762 Main St', 'Credit Card', 'Delivered', 'TRK70997648', 3, 'WINTER15', 'Facebook', 562.61),
 ('ORD200230', '2023-12-16 00:00:00', 'C94595', 'Desk', 4, 61.91, '948 Main St', 'Gift Card', 'Delivered', 'TRK24497305', 6, 'WINTER15', 'Email', 247.64),
 ('ORD200254', '2023-12-26 00:00:00', 'C10866', 'Monitor', 3, 263.19, '770 Main St', 'Online', 'Delivered', 'TRK34809583', 5, None, 'Instagram', 789.5699999999999),
 ('ORD200259', '2023-06-11 00:00:00', 'C20977', 'Chair', 4, 435.12, '636 Main St', 'Credit Card', 'Delivered', 'TRK54991561', 9, 'SAVE10', 'Instagram', 1740.48),
 ('ORD200261', '2025-05-28 00:00:00', 'C68976', 'Phone', 5, 173.65, '460 Main St', 'Gift Card', 'Delivered', 'TRK25491356', 9, 'SAVE10', 'Email', 868.25),
 ('ORD200267', '2025-04-17 00:00:00', 'C84480', 'Chair', 5, 468.51, '803 Main St', 'Debit Card', 'Delivered', 'TRK62361867', 9, None, 'Facebook', 2342.55),
 ('ORD200268', '2023-08-11 00:00:00', 'C37032', 'Phone', 2, 423.88, '655 Main St', 'Debit Card', 'Delivered', 'TRK48639226', 7, 'SAVE10', 'Referral', 847.76),
 ('ORD200277', '2024-09-09 00:00:00', 'C11210', 'Chair', 5, 90.92, '910 Main St', 'Credit Card', 'Delivered', 'TRK44929965', 9, 'SAVE10', 'Facebook', 454.6),
 ('ORD200278', '2024-11-18 00:00:00', 'C46015', 'Laptop', 5, 362.46, '299 Main St', 'Cash', 'Delivered', 'TRK46598430', 6, 'FREESHIP', 'Instagram', 1812.3),
 ('ORD200280', '2023-03-27 00:00:00', 'C55388', 'Tablet', 3, 404.62, '740 Main St', 'Gift Card', 'Delivered', 'TRK75741001', 6, 'FREESHIP', 'Instagram', 1213.86),
 ('ORD200285', '2025-06-10 00:00:00', 'C67583', 'Phone', 1, 338.31, '974 Main St', 'Online', 'Delivered', 'TRK93281700', 3, None, 'Google', 338.31),
 ('ORD200290', '2023-05-05 00:00:00', 'C24901', 'Chair', 3, 99.9, '258 Main St', 'Cash', 'Delivered', 'TRK14029489', 8, 'FREESHIP', 'Facebook', 299.7),
 ('ORD200291', '2024-05-12 00:00:00', 'C61521', 'Phone', 2, 345.01, '670 Main St', 'Credit Card', 'Delivered', 'TRK93676567', 6, 'FREESHIP', 'Google', 690.02),
 ('ORD200292', '2025-01-15 00:00:00', 'C39639', 'Monitor', 1, 65.95, '185 Main St', 'Credit Card', 'Delivered', 'TRK31042152', 5, None, 'Facebook', 65.95),
 ('ORD200304', '2024-10-18 00:00:00', 'C86762', 'Monitor', 5, 408.73, '326 Main St', 'Gift Card', 'Delivered', 'TRK75686292', 10, 'FREESHIP', 'Instagram', 2043.65),
 ('ORD200307', '2023-07-01 00:00:00', 'C92407', 'Laptop', 3, 557.41, '135 Main St', 'Online', 'Delivered', 'TRK11755610', 4, None, 'Email', 1672.23),
 ('ORD200309', '2023-10-03 00:00:00', 'C63153', 'Chair', 4, 549.76, '625 Main St', 'Debit Card', 'Delivered', 'TRK38033305', 4, 'FREESHIP', 'Facebook', 2199.04),
 ('ORD200313', '2023-07-09 00:00:00', 'C67687', 'Chair', 2, 434.3, '978 Main St', 'Cash', 'Delivered', 'TRK22838735', 7, 'SAVE10', 'Instagram', 868.6),
 ('ORD200314', '2023-10-04 00:00:00', 'C29931', 'Desk', 4, 153.09, '540 Main St', 'Online', 'Delivered', 'TRK48712417', 4, 'FREESHIP', 'Referral', 612.36),
 ('ORD200322', '2024-06-14 00:00:00', 'C48646', 'Phone', 5, 231.82, '339 Main St', 'Debit Card', 'Delivered', 'TRK18233748', 6, 'SAVE10', 'Facebook', 1159.1),
 ('ORD200331', '2023-04-15 00:00:00', 'C78724', 'Printer', 3, 422.13, '187 Main St', 'Online', 'Delivered', 'TRK25703134', 7, 'SAVE10', 'Facebook', 1266.39),
 ('ORD200334', '2024-03-26 00:00:00', 'C90348', 'Chair', 4, 224.75, '728 Main St', 'Online', 'Delivered', 'TRK20635777', 7, 'WINTER15', 'Facebook', 899.0),
 ('ORD200349', '2023-11-30 00:00:00', 'C39648', 'Chair', 1, 465.33, '824 Main St', 'Gift Card', 'Delivered', 'TRK56016905', 2, 'FREESHIP', 'Google', 465.33),
 ('ORD200351', '2025-02-15 00:00:00', 'C94248', 'Laptop', 1, 64.66, '494 Main St', 'Debit Card', 'Delivered', 'TRK89406816', 4, None, 'Instagram', 64.66),
 ('ORD200353', '2025-03-28 00:00:00', 'C16012', 'Tablet', 1, 630.82, '171 Main St', 'Online', 'Delivered', 'TRK15195225', 5, 'FREESHIP', 'Google', 630.82),
 ('ORD200357', '2023-07-08 00:00:00', 'C74982', 'Laptop', 5, 408.56, '398 Main St', 'Debit Card', 'Delivered', 'TRK98700702', 8, 'FREESHIP', 'Instagram', 2042.8),
 ('ORD200359', '2023-06-09 00:00:00', 'C95643', 'Desk', 4, 606.57, '303 Main St', 'Debit Card', 'Delivered', 'TRK23286689', 5, 'WINTER15', 'Referral', 2426.28),
 ('ORD200361', '2024-06-29 00:00:00', 'C53464', 'Printer', 5, 659.85, '197 Main St', 'Credit Card', 'Delivered', 'TRK32743531', 9, 'SAVE10', 'Facebook', 3299.25),
 ('ORD200385', '2023-10-31 00:00:00', 'C56851', 'Chair', 5, 191.63, '752 Main St', 'Gift Card', 'Delivered', 'TRK65290904', 6, 'FREESHIP', 'Facebook', 958.15),
 ('ORD200390', '2023-07-14 00:00:00', 'C55996', 'Printer', 5, 508.69, '885 Main St', 'Cash', 'Delivered', 'TRK30547638', 10, 'FREESHIP', 'Google', 2543.45),
 ('ORD200392', '2024-02-28 00:00:00', 'C95100', 'Phone', 1, 627.2, '197 Main St', 'Online', 'Delivered', 'TRK47366265', 1, 'WINTER15', 'Email', 627.2),
 ('ORD200395', '2025-04-25 00:00:00', 'C30010', 'Phone', 3, 127.41, '830 Main St', 'Gift Card', 'Delivered', 'TRK35386084', 7, 'SAVE10', 'Referral', 382.23),
 ('ORD200404', '2023-03-09 00:00:00', 'C45482', 'Monitor', 2, 99.1, '440 Main St', 'Cash', 'Delivered', 'TRK54571699', 6, None, 'Instagram', 198.2),
 ('ORD200409', '2023-06-28 00:00:00', 'C45187', 'Desk', 5, 84.13, '767 Main St', 'Online', 'Delivered', 'TRK12320793', 9, 'SAVE10', 'Google', 420.65),
 ('ORD200413', '2023-10-08 00:00:00', 'C13923', 'Tablet', 1, 118.8, '123 Main St', 'Online', 'Delivered', 'TRK87598790', 6, 'SAVE10', 'Email', 118.8),
 ('ORD200414', '2025-05-04 00:00:00', 'C11829', 'Desk', 2, 139.57, '797 Main St', 'Cash', 'Delivered', 'TRK84229257', 4, 'WINTER15', 'Facebook', 279.14),
 ('ORD200437', '2024-04-18 00:00:00', 'C63378', 'Phone', 1, 512.39, '955 Main St', 'Online', 'Delivered', 'TRK20863705', 2, 'FREESHIP', 'Instagram', 512.39),
 ('ORD200445', '2024-03-23 00:00:00', 'C94569', 'Phone', 1, 487.21, '227 Main St', 'Cash', 'Delivered', 'TRK31351770', 3, 'SAVE10', 'Referral', 487.21),
 ('ORD200446', '2023-10-18 00:00:00', 'C89592', 'Laptop', 5, 509.58, '262 Main St', 'Online', 'Delivered', 'TRK49442402', 6, 'FREESHIP', 'Instagram', 2547.9),
 ('ORD200466', '2023-07-18 00:00:00', 'C37412', 'Phone', 1, 432.47, '895 Main St', 'Cash', 'Delivered', 'TRK97829604', 4, 'FREESHIP', 'Referral', 432.47),
 ('ORD200468', '2025-06-21 00:00:00', 'C90110', 'Phone', 1, 418.36, '998 Main St', 'Credit Card', 'Delivered', 'TRK60203957', 5, 'FREESHIP', 'Email', 418.36),
 ('ORD200481', '2023-04-23 00:00:00', 'C94568', 'Laptop', 4, 484.85, '317 Main St', 'Debit Card', 'Delivered', 'TRK58653915', 5, 'WINTER15', 'Referral', 1939.4),
 ('ORD200508', '2025-05-14 00:00:00', 'C39550', 'Phone', 1, 558.27, '976 Main St', 'Online', 'Delivered', 'TRK24120267', 1, None, 'Referral', 558.27),
 ('ORD200510', '2024-12-16 00:00:00', 'C72533', 'Printer', 1, 376.76, '389 Main St', 'Debit Card', 'Delivered', 'TRK51288986', 5, 'SAVE10', 'Email', 376.76),
 ('ORD200511', '2024-03-15 00:00:00', 'C11415', 'Monitor', 5, 575.24, '267 Main St', 'Cash', 'Delivered', 'TRK65061457', 7, 'WINTER15', 'Email', 2876.2),
 ('ORD200531', '2024-07-02 00:00:00', 'C64502', 'Desk', 5, 320.01, '722 Main St', 'Gift Card', 'Delivered', 'TRK14914388', 6, None, 'Referral', 1600.05),
 ('ORD200532', '2025-05-03 00:00:00', 'C47365', 'Laptop', 2, 41.0, '369 Main St', 'Online', 'Delivered', 'TRK42207882', 7, None, 'Email', 82.0),
 ('ORD200537', '2025-03-23 00:00:00', 'C68553', 'Tablet', 3, 247.47, '385 Main St', 'Online', 'Delivered', 'TRK58218971', 4, 'SAVE10', 'Facebook', 742.41),
 ('ORD200539', '2025-02-18 00:00:00', 'C53277', 'Desk', 3, 531.72, '473 Main St', 'Gift Card', 'Delivered', 'TRK17653832', 7, 'SAVE10', 'Google', 1595.16),
 ('ORD200547', '2023-08-20 00:00:00', 'C40427', 'Phone', 1, 613.98, '411 Main St', 'Online', 'Delivered', 'TRK25392280', 4, 'FREESHIP', 'Facebook', 613.98),
 ('ORD200548', '2024-01-05 00:00:00', 'C17103', 'Printer', 3, 426.12, '922 Main St', 'Online', 'Delivered', 'TRK64398650', 5, 'WINTER15', 'Instagram', 1278.36),
 ('ORD200551', '2023-05-18 00:00:00', 'C23947', 'Laptop', 1, 120.98, '353 Main St', 'Debit Card', 'Delivered', 'TRK74812710', 6, 'WINTER15', 'Email', 120.98),
 ('ORD200558', '2024-07-16 00:00:00', 'C76766', 'Phone', 4, 628.12, '485 Main St', 'Online', 'Delivered', 'TRK32052962', 6, 'WINTER15', 'Instagram', 2512.48),
 ('ORD200568', '2023-03-10 00:00:00', 'C29072', 'Laptop', 2, 343.99, '312 Main St', 'Online', 'Delivered', 'TRK72334047', 4, None, 'Google', 687.98),
 ('ORD200578', '2024-10-10 00:00:00', 'C50415', 'Monitor', 5, 566.07, '587 Main St', 'Credit Card', 'Delivered', 'TRK41345634', 6, 'SAVE10', 'Instagram', 2830.35),
 ('ORD200580', '2023-11-14 00:00:00', 'C71076', 'Monitor', 2, 255.99, '340 Main St', 'Credit Card', 'Delivered', 'TRK65148292', 4, 'SAVE10', 'Instagram', 511.98),
 ('ORD200581', '2024-11-11 00:00:00', 'C44674', 'Laptop', 1, 627.34, '942 Main St', 'Online', 'Delivered', 'TRK87158684', 1, None, 'Referral', 627.34),
 ('ORD200583', '2025-06-15 00:00:00', 'C27072', 'Chair', 3, 154.37, '996 Main St', 'Gift Card', 'Delivered', 'TRK29750379', 4, None, 'Instagram', 463.11),
 ('ORD200584', '2025-03-21 00:00:00', 'C15257', 'Chair', 4, 145.05, '626 Main St', 'Online', 'Delivered', 'TRK28779938', 6, 'SAVE10', 'Google', 580.2),
 ('ORD200587', '2023-06-12 00:00:00', 'C18820', 'Monitor', 5, 514.6, '347 Main St', 'Gift Card', 'Delivered', 'TRK91547425', 10, 'FREESHIP', 'Instagram', 2573.0),
 ('ORD200588', '2024-12-10 00:00:00', 'C61849', 'Monitor', 4, 577.82, '811 Main St', 'Credit Card', 'Delivered', 'TRK47613918', 9, None, 'Google', 2311.28),
 ('ORD200589', '2025-02-10 00:00:00', 'C84041', 'Laptop', 2, 500.8, '900 Main St', 'Cash', 'Delivered', 'TRK84920444', 3, 'FREESHIP', 'Referral', 1001.6),
 ('ORD200604', '2025-06-22 00:00:00', 'C99214', 'Chair', 3, 32.62, '252 Main St', 'Debit Card', 'Delivered', 'TRK81368481', 6, None, 'Facebook', 97.85999999999999),
 ('ORD200621', '2023-10-22 00:00:00', 'C37455', 'Phone', 5, 476.01, '146 Main St', 'Credit Card', 'Delivered', 'TRK82685594', 7, 'WINTER15', 'Google', 2380.05),
 ('ORD200624', '2024-01-16 00:00:00', 'C25967', 'Tablet', 5, 341.96, '747 Main St', 'Debit Card', 'Delivered', 'TRK88559278', 6, None, 'Email', 1709.8),
 ('ORD200632', '2023-05-02 00:00:00', 'C67260', 'Laptop', 5, 678.16, '463 Main St', 'Gift Card', 'Delivered', 'TRK38229104', 7, 'WINTER15', 'Facebook', 3390.8),
 ('ORD200634', '2024-04-25 00:00:00', 'C66906', 'Printer', 2, 259.32, '117 Main St', 'Gift Card', 'Delivered', 'TRK31633755', 2, 'WINTER15', 'Referral', 518.64),
 ('ORD200638', '2023-10-15 00:00:00', 'C66840', 'Tablet', 4, 578.27, '547 Main St', 'Online', 'Delivered', 'TRK76929637', 9, 'WINTER15', 'Email', 2313.08),
 ('ORD200648', '2025-01-18 00:00:00', 'C89674', 'Monitor', 2, 575.83, '182 Main St', 'Online', 'Delivered', 'TRK45902512', 3, 'WINTER15', 'Referral', 1151.66),
 ('ORD200650', '2023-05-18 00:00:00', 'C74499', 'Desk', 2, 372.23, '518 Main St', 'Gift Card', 'Delivered', 'TRK93767278', 7, 'SAVE10', 'Email', 744.46),
 ('ORD200659', '2024-10-26 00:00:00', 'C24301', 'Phone', 2, 642.04, '964 Main St', 'Gift Card', 'Delivered', 'TRK55000075', 4, 'WINTER15', 'Email', 1284.08),
 ('ORD200673', '2023-02-21 00:00:00', 'C46504', 'Tablet', 2, 372.92, '131 Main St', 'Credit Card', 'Delivered', 'TRK95024356', 7, 'SAVE10', 'Email', 745.84),
 ('ORD200674', '2024-01-09 00:00:00', 'C56928', 'Laptop', 4, 358.75, '860 Main St', 'Gift Card', 'Delivered', 'TRK57792939', 9, 'SAVE10', 'Facebook', 1435.0),
 ('ORD200692', '2023-01-23 00:00:00', 'C25534', 'Desk', 5, 196.84, '319 Main St', 'Credit Card', 'Delivered', 'TRK68347402', 5, 'WINTER15', 'Instagram', 984.2),
 ('ORD200698', '2023-01-04 00:00:00', 'C44366', 'Laptop', 2, 388.22, '169 Main St', 'Cash', 'Delivered', 'TRK48658394', 2, 'WINTER15', 'Instagram', 776.44),
 ('ORD200701', '2024-06-23 00:00:00', 'C75456', 'Monitor', 3, 92.22, '115 Main St', 'Credit Card', 'Delivered', 'TRK90519490', 5, 'FREESHIP', 'Email', 276.66),
 ('ORD200704', '2023-06-03 00:00:00', 'C96034', 'Desk', 4, 30.27, '819 Main St', 'Online', 'Delivered', 'TRK87261034', 9, 'FREESHIP', 'Google', 121.08),
 ('ORD200715', '2024-07-26 00:00:00', 'C68266', 'Printer', 3, 653.63, '281 Main St', 'Online', 'Delivered', 'TRK96161062', 7, 'FREESHIP', 'Email', 1960.89),
 ('ORD200717', '2023-10-16 00:00:00', 'C50087', 'Chair', 3, 122.11, '707 Main St', 'Online', 'Delivered', 'TRK31143760', 4, 'WINTER15', 'Email', 366.33),
 ('ORD200721', '2024-03-18 00:00:00', 'C46557', 'Desk', 2, 118.59, '890 Main St', 'Credit Card', 'Delivered', 'TRK56110689', 2, None, 'Email', 237.18),
 ('ORD200726', '2024-10-25 00:00:00', 'C18105', 'Laptop', 4, 583.02, '338 Main St', 'Online', 'Delivered', 'TRK94006117', 4, 'FREESHIP', 'Facebook', 2332.08),
 ('ORD200730', '2025-02-22 00:00:00', 'C77357', 'Phone', 1, 474.6, '407 Main St', 'Debit Card', 'Delivered', 'TRK91943923', 4, 'SAVE10', 'Email', 474.6),
 ('ORD200732', '2025-03-07 00:00:00', 'C80987', 'Laptop', 1, 132.05, '787 Main St', 'Online', 'Delivered', 'TRK42187776', 2, None, 'Google', 132.05),

Observation:
The query displays only orders with a Delivered status.
    
Insight:
Delivered orders represent successfully completed customer purchases and can be used to analyze fulfilled sales.

In [34]:
%%sql
SELECT PaymentMethod, COUNT(*) AS TotalOrders FROM Orders
GROUP BY PaymentMethod
ORDER BY TotalOrders DESC;

 * sqlite:///project3.db
Done.

[('Online', 258),
 ('Cash', 246),
 ('Credit Card', 234),
 ('Debit Card', 232),
 ('Gift Card', 230)]

Observation:
Online payment has the highest number of orders.
    
Insight:
Customers prefer online payment methods over other payment options.

Final Insights

1. The dataset contains 1200 customer orders.

2. The average order value is ₹1053.97.

3. Total revenue generated is ₹12,64,761.96.

4. Printer is the most ordered product, while Phone is the least ordered.

5. Product demand varies across categories, with Printer and Tablet showing the highest popularity.

6. Delivered orders represent successfully completed transactions.

7. SQL queries such as COUNT, AVG, SUM, GROUP BY, ORDER BY, and WHERE helped uncover key business insights from the dataset.